[package]
name = "sp1-recursion-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-air = { workspace = true }
p3-field = { workspace = true }
p3-commit = { workspace = true }
p3-fri = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-util = { workspace = true }
p3-symmetric = { workspace = true }
p3-challenger = { workspace = true }
p3-baby-bear = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-poseidon2 = { workspace = true }
sp1-recursion-core = { path = "../core" }
sp1-recursion-compiler = { path = "../compiler" }
sp1-core = { path = "../../core" }
itertools = "0.12.1"
serde = { version = "1.0.201", features = ["derive"] }
rand = "0.8.5"
array-macro = "2.1.8"
tracing = "0.1.40"
