[package]
name = "sp1-eval"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-core = { path = "../core" }
sp1-prover = { path = "../prover" }

clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
serde = "1.0.201"
